ShopDb/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;

namespace ShopDb.Models
{
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            ShoppingCartRows = new HashSet<ShoppingCartRow>();
        }

        public int Id { get; set; }
        public int? UserId { get; set; }

        public virtual User? User { get; set; }
        public virtual ICollection<ShoppingCartRow> ShoppingCartRows { get; set; }
    }
}

ShopDb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopDb.Models;
using System.Diagnostics;

namespace ShopDb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _conf;
        private readonly ShopDbContext _shopDb;

        public HomeController(ILogger<HomeController> logger, IConfiguration conf)
        {
            _logger = logger;
            _conf = conf;

            var optionsBuilder = new DbContextOptionsBuilder<ShopDbContext>();
            optionsBuilder.UseSqlServer(_conf["ConnectionStrings:ShopDb"]);
            _shopDb = new ShopDbContext(optionsBuilder.Options);
        }

        public IActionResult Index()
        {
            var topProducts = GetTopProducts(4);

            return View(topProducts);
        }

        public IActionResult ShoppingCart()
        {
            var userId = HttpContext.Session.GetInt32("userId");
            var cartId = _shopDb.ShoppingCarts.Where(c => c.UserId == userId).Select(c => c.Id).FirstOrDefault();
            var cartRows = _shopDb.ShoppingCartRows.Include(c => c.Product).Where(x => x.ShoppingCartId == cartId);
            return View(cartRows.ToList());
        }

        public IActionResult AddToCart(int id, int quantity = 1)
        {
            var userId = HttpContext.Session.GetInt32("userId");
            var cartId = _shopDb.ShoppingCarts.Where(c => c.UserId == userId).Select(c => c.Id).FirstOrDefault();

            // Check if user already has an active ShoppingCart, else create new ShoppingCart
            if (cartId == 0)
            {
                var cart = new ShoppingCart() { UserId = userId };
                _shopDb.ShoppingCarts.Add(cart);
                _shopDb.SaveChanges();
                cartId = cart.Id;
            }

            // Check if ShoppingCart already includes the product, else add new ShoppingCartRow for the product
            var cartRow = _shopDb.ShoppingCartRows.Where(r => r.ShoppingCartId == cartId && r.ProductId == id).FirstOrDefault();

            if (cartRow is null)
            {
                cartRow = new ShoppingCartRow() { ProductId = id, ShoppingCartId = cartId, Quantity = quantity };
                _shopDb.ShoppingCartRows.Add(cartRow);
            }
            else
            {
                cartRow.Quantity += quantity;
            }
            _shopDb.SaveChanges();

            return RedirectToAction("ShoppingCart");
        }

        public IActionResult DeleteFromCart(int id, int quantity = 1)
        {
            var cartRow = _shopDb.ShoppingCartRows.Where(r => r.Id == id).FirstOrDefault();

            if (cartRow.Quantity > quantity)
            {
                cartRow.Quantity -= quantity;
            }
            else
            {
                _shopDb.ShoppingCartRows.Remove(cartRow);
            }
            _shopDb.SaveChanges();

            return RedirectToAction("ShoppingCart");
        }

        public IActionResult ConfirmOrder(int id, decimal total)
        {
            var cart = _shopDb.ShoppingCarts.Where(c => c.Id == id).FirstOrDefault();

            var order = new Order()
            {
                UserId = (int)HttpContext.Session.GetInt32("userId"),
                Date = DateTime.Today,
                TotalPrice = total
            };

            _shopDb.Orders.Add(order);
            _shopDb.SaveChanges();

            var cartRows = _shopDb.ShoppingCartRows.Include(c => c.Product).Where(x => x.ShoppingCartId == id).ToList();

            // Create new OrderRow for each ShoppingCartRow and delete the whole cart after
            foreach (var item in cartRows)
            {
                item.Product.Quantity -= item.Quantity;

                var orderRow = new OrderRow()
                {
                    OrderId = order.Id,
                    ProductId = item.ProductId,
                    Quantity = item.Quantity,
                    Price = item.Product.Price
                };
                _shopDb.OrderRows.Add(orderRow);
                _shopDb.ShoppingCartRows.Remove(item);
            }

            _shopDb.SaveChanges();
            _shopDb.ShoppingCarts.Remove(cart);
            _shopDb.SaveChanges();

            return View(cartRows);
        }
        public List<Product> GetTopProducts(int quantity)
        {
            var topProductsDict = new Dictionary<int, int>();
            var topProductsList = new List<Product>();

            // Count how many items of each product sold
            foreach (var item in _shopDb.OrderRows)
            {
                if (!topProductsDict.ContainsKey(item.ProductId))
                {
                    topProductsDict.Add(item.ProductId, item.Quantity);
                }
                else
                {
                    topProductsDict[item.ProductId] += item.Quantity;
                }
            }

            foreach (var item in topProductsDict.OrderByDescending(p => p.Value))
            {
                var product = _shopDb.Product.Where(p => p.Id == item.Key).First();
                topProductsList.Add(product);
            }

            return topProductsList.Take(quantity).ToList();
        }
    }
}

ShopDb/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopDb.Models;

namespace ShopDb.Controllers
{
    public class ProductController : Controller
    {
        private readonly ShopDbContext _context;
        private readonly IConfiguration _conf;
        private readonly ShopDbContext _shopDb;

        public ProductController(ShopDbContext context, IConfiguration conf)
        {
            _context = context;
            _conf = conf;

            var optionsBuilder = new DbContextOptionsBuilder<ShopDbContext>();
            optionsBuilder.UseSqlServer(_conf["ConnectionStrings:ShopDb"]);
            _shopDb = new ShopDbContext(optionsBuilder.Options);
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Header = "Kaikki tuotteet";
            var allProducts = _context.Product.Include(p => p.Category);
            return View(await allProducts.ToListAsync());
        }

        public async Task<IActionResult> GetProductsByCategory(int id)
        {
            var products = _context.Product.Include(p => p.Category).Where(i => i.Category.Id == id);
            ViewBag.Header = products.First().Category.Name;
            return View("Index", await products.ToListAsync());
        }
        [HttpPost]
        public async Task<IActionResult> GetProductsByName(string name)
        {

            if (string.IsNullOrEmpty(name))
            {
                return RedirectToAction("Index", "Home");
            }
            var search = name.ToLower().Trim();
            var shopDbContext = _context.Product.Where(i => i.Name.ToLower().Contains(search)).Include(p => p.Category);
            if (shopDbContext.ToList().Count() == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Header = $"Haun \"{name}\" tulokset, {shopDbContext.ToList().Count().ToString()} kpl";
            return View("Index", await shopDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            var userId = HttpContext.Session.GetInt32("userId");
            var like = _context.Likes
                .Where(a => a.UserId.Equals(userId) && a.ProductId.Equals(id))
                .FirstOrDefault();

            product.Like = like;
            return View(product);
        }

        private bool ProductExists(int id)
        {
          return (_context.Product?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ShopDb/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopDb.Models;

namespace ShopDb.Controllers
{
    public class UserController : Controller
    {
        private readonly ShopDbContext _context;
        private readonly IConfiguration _conf;

        public UserController(ShopDbContext context, IConfiguration conf)
        {
            _conf = conf;
            var optionsBuilder = new DbContextOptionsBuilder<ShopDbContext>();
            optionsBuilder.UseSqlServer(_conf["ConnectionStrings:ShopDb"]);
            _context = new ShopDbContext(optionsBuilder.Options);
        }

        [HttpGet]
        public IActionResult NewUser()
        {
            return View();
        }

        [HttpPost]
        public IActionResult NewUser(string firstName, string lastName, string phone, string email, string address, string postalCode, string city)
        {
            User user = new User()
            {
                FirstName = firstName,
                LastName = lastName,
                Phone = phone,
                Email = email
            };
            _context.Users.Add(user);

            
            HttpContext.Session.SetString("userName", user.FirstName + " " + user.LastName);

            Address address1 = new Address()
            {
                UserId = user.Id,
                Address1 = address,
                PostalCode = postalCode,
                City = city
            };
            _context.Addresses.Add(address1);
            user.Addresses.Add(address1);

            if (!Models.Utils.UserValidator(user, HttpContext))
            {
                return View();
            }
            
            _context.SaveChanges();
            HttpContext.Session.SetInt32("userId", user.Id);

            return RedirectToAction("Index", "Home");
        }

        private bool UserExists(int id)
        {
            return (_context.Users?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(User user)
        {
            if (UserExists(user.Id))
            {
                {
                    var obj = _context.Users.Where(a => a.Id.Equals(user.Id)).FirstOrDefault();

                    if (obj.Id == int.Parse(_conf["AdminId"]))
                    { return Redirect("/Admin/Product"); }

                    if (obj != null)
                    {
                        HttpContext.Session.SetInt32("userId", obj.Id);
                        HttpContext.Session.SetString("userName", obj.FirstName + " " + obj.LastName);
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            ViewBag.LoginFailedMessage = "Käyttäjä ID:tä ei löydy. Ole hyvä ja yritä uudelleen tai luo uusi käyttäjätili";
            return View(user);
        }

        public IActionResult ProfilePage()
        {
            if (HttpContext.Session.GetInt32("userId") != null)
            {
                var user = _context.Users.Include(a => a.Addresses).Where(i => i.Id == HttpContext.Session.GetInt32("userId")).FirstOrDefault();
                return View(user);
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        [HttpPost]
        public IActionResult UpdateProfile(string firstName, string lastName, string phone, string email, string address, string postalCode, string city)
        {
            User user = _context.Users.Include(a => a.Addresses).Where(i => i.Id.Equals(HttpContext.Session.GetInt32("userId"))).FirstOrDefault();
            user.FirstName = firstName;
            user.LastName = lastName;
            user.Phone = phone;
            user.Email = email;
            user.Addresses.FirstOrDefault().Address1 = address;
            user.Addresses.FirstOrDefault().PostalCode = postalCode;
            user.Addresses.FirstOrDefault().City = city;

            if (!Models.Utils.UserValidator(user, HttpContext))
            {
                return View("ProfilePage", user);
            }
            _context.Update(user);
            _context.SaveChanges();

            return View("ProfilePage", user);
        }

        public IActionResult OrderHistory()
        {
            var userId = HttpContext.Session.GetInt32("userId");
            var orders = _context.Orders.Where(o => o.UserId == userId).ToList();

            return View(orders);
        }

        public IActionResult OrderDetails(int id)
        {
            var orderRows = _context.OrderRows.Include(o => o.Order).Include(p => p.Product).Where(r => r.OrderId == id).ToList();

            return View(orderRows);
        }

        public IActionResult LogOut()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }


        public async Task<IActionResult> AddLike(int id)
        {
            var userId = HttpContext.Session.GetInt32("userId");
            var like = new Like()
            {
                UserId = (int)userId,
                ProductId = id
            };

            _context.Likes.Add(like);
            _context.SaveChanges();

            var product = await _context.Product
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (product == null)
            {
                return NotFound();
            }

            return Redirect("/Product/Details/" + id + "/" + product.Name);
        }

        public async Task<IActionResult> RemoveLike(int id)
        {
            var userId = HttpContext.Session.GetInt32("userId");
            var like = _context.Likes.Where(a => a.UserId.Equals(userId) && a.ProductId.Equals(id))
                .FirstOrDefault();


            _context.Likes.Remove(like);
            _context.SaveChanges();

            var product = await _context.Product
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (product == null)
            {
                return NotFound();
            }

            return Redirect("/Product/Details/" + id + "/" + product.Name);
        }
    }
}

ShopDb/Views/Home/ConfirmOrder.cshtml
@using System.Globalization
@model IEnumerable<ShopDb.Models.ShoppingCartRow>

@{
    ViewData["Title"] = "ConfirmOrder";
}

<div class="p-4 bg-light bg-semitransparent text-center">
<h1 class="navbar-brand" style="color: #5e9693;">Maksu vahvistettu! Tilauksen tiedot:</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                Tuote
            </th>
            <th>
                Hinta
            </th>
            <th>
                Lkm
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Price) €
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="text-center">
    <table class="table">
        <tr>
            <td>
                Yhteensä:
            </td>
            <td>
                @Model.Sum(m => m.Product.Price * m.Quantity) €
            </td>
        </tr>
        <tr>
            <td>
                Toimitus:
            </td>
            <td>
                @DateTime.Today.AddDays(3).ToString("dd.MM.yyyy", CultureInfo.CreateSpecificCulture("fi-FI"))
            </td>
        </tr>
    </table>
</div>

@Html.ActionLink("Kaikki tilaukset", "OrderHistory", "User", null, new {@class="btn btn-secondary"})

                </div>

ShopDb/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor
@model List<Product>

@{
    ViewData["Title"] = "Home Page";
}

<section class="text-center navbar-brand" style="font-size: 9vw; margin-bottom:9vw">
<span style="color: #5e9693;">Kaluste</span><span style="color: #fff;">.Net</span>
 </section>

<!--Section: Top Sold Products -->
      <section class="text-center">
        <h1 class="mb-5 navbar-brand"  style="color: #5e9693;"><strong>Suosituimmat tuotteet</strong></h1>

        <div class="row">
            @foreach (var item in Model)
        {
          <div class="col-lg-3 col-md-4 mb-4">
            <div class="card">
              <div class="imagesquare bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                <img src="@(item.PictureUrl!=null ? item.PictureUrl : "https://mdbootstrap.com/img/new/standard/nature/184.jpg")" class="p-3 img-fluid" />
                <a href="#!">
                  <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                </a>
              </div>
              <div class="card-body">
                <h5 class="card-title">@item.Name</h5>
                <p class="card-text">
                  @item.Price €
                </p>
                <a href="/Product/Details/@item.Id/@item.Name" class="btn btn-secondary">Tuotteen tiedot</a>
              </div>
            </div>
          </div>
        }
        </div>
      </section>
      <!--Section:  Top Sold Products -->

ShopDb/Views/Home/ShoppingCart.cshtml
@model IEnumerable<ShopDb.Models.ShoppingCartRow>

@{
    ViewData["Title"] = "Ostoskori";
}
<div class="p-4 bg-light bg-semitransparent text-center">
<h1 class="navbar-brand" style="color: #5e9693;">Ostoskori</h1>

@{if (Model.Count() < 1)
    {
    <p>Ostoskori on tyhjä</p>
    }
else
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    Tuote
                </th>
                <th>
                    Hinta
                </th>
                <th>
                    Lkm
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Price) €
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity) kpl
                </td>
                <td>
                    @Html.ActionLink("Tuotteen tiedot", "Details", "Product", new {id = item.ProductId}, new {@class="btn btn-light"})
                    @Html.ActionLink("Poista tuote korista", "DeleteFromCart", "Home", new {item.Id}, new {@class="btn btn-light"})
                </td>
            </tr>
}
        </tbody>
    </table>
    <div class="text-center">
    Yhteensä: @Model.Sum(m => m.Product.Price * m.Quantity) €
</div>
<br/>
<div class="text-center">
@Html.ActionLink("Siirry maksamaan", "ConfirmOrder", "Home", new {id = Model.First().ShoppingCartId, total = Model.Sum(m => m.Product.Price * m.Quantity) }, new {@class="btn btn-secondary"})
</div>
}
}
</div>